#ifndef _VINBERO_COMMON_ERROR_H
#define _VINBERO_COMMON_ERROR_H

#include <errno.h>

#define VINBERO_COMMON_ERROR_AGAIN 1
#define VINBERO_COMMON_ERROR_ALREADY 2
#define VINBERO_COMMON_ERROR_DLOPEN 3
#define VINBERO_COMMON_ERROR_DLSYM 4
#define VINBERO_COMMON_ERROR_FO 3
#define VINBERO_COMMON_ERROR_INVALID_ARG 4
#define VINBERO_COMMON_ERROR_INVALID_CONFIG 5
#define VINBERO_COMMON_ERROR_INVALID_MODULE 6
#define VINBERO_COMMON_ERROR_IO 7
#define VINBERO_COMMON_ERROR_UNKNOWN 8
#define VINBERO_COMMON_ERROR_PERMISSION 9
#define VINBERO_COMMON_ERROR_OUT_OF_RANGE 10

#endif
