#ifndef _VINBERO_COM_STATUS_H
#define _VINBERO_COM_STATUS_H

#define VINBERO_COM_STATUS_SUCCESS 0
#define VINBERO_COM_STATUS_CONTINUE 1
#define VINBERO_COM_STATUS_AGAIN 2
#define VINBERO_COM_STATUS_EXIT 3

#endif
