#ifndef _VINBERO_COMMON_ERROR_H
#define _VINBERO_COMMON_ERROR_H

#include <errno.h>

#define VINBERO_COMMON_ERROR_AGAIN
#define VINBERO_COMMON_ERROR_FO
#define VINBERO_COMMON_ERROR_INVALID_ARG
#define VINBERO_COMMON_ERROR_INVALID_CONFIG
#define VINBERO_COMMON_ERROR_IO
#define VINBERO_COMMON_ERROR_UNKNOWN
#define VINBERO_COMMON_ERROR_PERMISSION
#define VINBERO_COMMON_ERROR_OUT_OF_RANGE

#endif
