#ifndef _VINBERO_COM_ERROR_H
#define _VINBERO_COM_ERROR_H

#define VINBERO_COM_ERROR_AGAIN -1
#define VINBERO_COM_ERROR_ALREADY -2
#define VINBERO_COM_ERROR_DLOPEN -3
#define VINBERO_COM_ERROR_DLSYM -4
#define VINBERO_COM_ERROR_FO -5
#define VINBERO_COM_ERROR_INVALID_ARG -6
#define VINBERO_COM_ERROR_INVALID_CONFIG -7
#define VINBERO_COM_ERROR_INVALID_MODULE -8
#define VINBERO_COM_ERROR_INVALID_OPTION -9
#define VINBERO_COM_ERROR_IO -10
#define VINBERO_COM_ERROR_UNKNOWN -11
#define VINBERO_COM_ERROR_PERMISSION -12
#define VINBERO_COM_ERROR_NULL -13
#define VINBERO_COM_ERROR_NO_SPACE -14
#define VINBERO_COM_ERROR_NO_MEMORY -15
#define VINBERO_COM_ERROR_READ -16
#define VINBERO_COM_ERROR_WRITE -17
#define VINBERO_COM_ERROR_RANGE -18
#define VINBERO_COM_ERROR_INVALID_DATA -19
#define VINBERO_COM_ERROR_NOT_FOUND -20

#endif
