#ifndef _VINBERO_COMMON_ERROR_H
#define _VINBERO_COMMON_ERROR_H

#define VINBERO_COMMON_ERROR_AGAIN -1
#define VINBERO_COMMON_ERROR_ALREADY -2
#define VINBERO_COMMON_ERROR_DLOPEN -3
#define VINBERO_COMMON_ERROR_DLSYM -4
#define VINBERO_COMMON_ERROR_FO -5
#define VINBERO_COMMON_ERROR_INVALID_ARG -6
#define VINBERO_COMMON_ERROR_INVALID_CONFIG -7
#define VINBERO_COMMON_ERROR_INVALID_MODULE -8
#define VINBERO_COMMON_ERROR_INVALID_OPTION -9
#define VINBERO_COMMON_ERROR_IO -10
#define VINBERO_COMMON_ERROR_UNKNOWN -11
#define VINBERO_COMMON_ERROR_PERMISSION -12
#define VINBERO_COMMON_ERROR_NULL -13

#endif
