#ifndef _VINBERO_COMMON_STATUS_H
#define _VINBERO_COMMON_STATUS_H

#define VINBERO_COMMON_STATUS_SUCCESS 0
#define VINBERO_COMMON_STATUS_CONTINUE 1
#define VINBERO_COMMON_STATUS_AGAIN 2
#define VINBERO_COMMON_STATUS_EXIT 3

#endif
