#ifndef _VINBERO_COMMON_ERRNO_H
#define _VINBERO_COMMON_ERRNO_H

#include <errno.h>

#if E2BIG <= 0
#define VINBERO_COMMON_ERRNO_2BIG E2BIG
#else
#define VINBERO_COMMON_ERRNO_2BIG -E2BIG
#endif

#if EACCES <= 0
#define VINBERO_COMMON_ERRNO_ACCES EACCES
#else
#define VINBERO_COMMON_ERRNO_ACCES -EACCES
#endif

#if EADDRINUSE <= 0
#define VINBERO_COMMON_ERRNO_ADDRINUSE EADDRINUSE
#else
#define VINBERO_COMMON_ERRNO_ADDRINUSE -EADDRINUSE
#endif

#if EADDRNOTAVAIL <= 0
#define VINBERO_COMMON_ERRNO_ADDRNOTAVAIL EADDRNOTAVAIL
#else
#define VINBERO_COMMON_ERRNO_ADDRNOTAVAIL -EADDRNOTAVAIL
#endif

#if EAFNOSUPPORT <= 0
#define VINBERO_COMMON_ERRNO_AFNOSUPPORT EAFNOSUPPORT
#else
#define VINBERO_COMMON_ERRNO_AFNOSUPPORT -EAFNOSUPPORT
#endif

#if EAGAIN <= 0
#define VINBERO_COMMON_ERRNO_AGAIN EAGAIN
#else
#define VINBERO_COMMON_ERRNO_AGAIN -EAGAIN
#endif

#if EALREADY <= 0
#define VINBERO_COMMON_ERRNO_ALREADY EALREADY
#else
#define VINBERO_COMMON_ERRNO_ALREADY -EALREADY
#endif

#if EBADE <= 0
#define VINBERO_COMMON_ERRNO_BADE EBADE
#else
#define VINBERO_COMMON_ERRNO_BADE -EBADE
#endif

#if EBADF <= 0
#define VINBERO_COMMON_ERRNO_BADF EBADF
#else
#define VINBERO_COMMON_ERRNO_BADF -EBADF
#endif

#if EBADFD <= 0
#define VINBERO_COMMON_ERRNO_BADFD EBADFD
#else
#define VINBERO_COMMON_ERRNO_BADFD -EBADFD
#endif

#if EBADMSG <= 0
#define VINBERO_COMMON_ERRNO_BADMSG EBADMSG
#else
#define VINBERO_COMMON_ERRNO_BADMSG -EBADMSG
#endif

#if EBADR <= 0
#define VINBERO_COMMON_ERRNO_BADR EBADR
#else
#define VINBERO_COMMON_ERRNO_BADR -EBADR
#endif

#if EBADRQC <= 0
#define VINBERO_COMMON_ERRNO_BADRQC EBADRQC
#else
#define VINBERO_COMMON_ERRNO_BADRQC -EBADRQC
#endif

#if EBADSLT <= 0
#define VINBERO_COMMON_ERRNO_BADSLT EBADSLT
#else
#define VINBERO_COMMON_ERRNO_BADSLT -EBADSLT
#endif

#if EBUSY <= 0
#define VINBERO_COMMON_ERRNO_BUSY EBUSY
#else
#define VINBERO_COMMON_ERRNO_BUSY -EBUSY
#endif

#if ECANCELED <= 0
#define VINBERO_COMMON_ERRNO_CANCELED ECANCELED
#else
#define VINBERO_COMMON_ERRNO_CANCELED -ECANCELED
#endif

#if ECHILD <= 0
#define VINBERO_COMMON_ERRNO_CHILD ECHILD
#else
#define VINBERO_COMMON_ERRNO_CHILD -ECHILD
#endif

#if ECHRNG <= 0
#define VINBERO_COMMON_ERRNO_CHRNG ECHRNG
#else
#define VINBERO_COMMON_ERRNO_CHRNG -ECHRNG
#endif

#if ECOMM <= 0
#define VINBERO_COMMON_ERRNO_COMM ECOMM
#else
#define VINBERO_COMMON_ERRNO_COMM -ECOMM
#endif

#if ECONNABORTED <= 0
#define VINBERO_COMMON_ERRNO_CONNABORTED ECONNABORTED
#else
#define VINBERO_COMMON_ERRNO_CONNABORTED -ECONNABORTED
#endif

#if ECONNREFUSED <= 0
#define VINBERO_COMMON_ERRNO_CONNREFUSED ECONNREFUSED
#else
#define VINBERO_COMMON_ERRNO_CONNREFUSED -ECONNREFUSED
#endif

#if ECONNRESET <= 0
#define VINBERO_COMMON_ERRNO_CONNRESET ECONNRESET
#else
#define VINBERO_COMMON_ERRNO_CONNRESET -ECONNRESET
#endif

#if EDEADLK <= 0
#define VINBERO_COMMON_ERRNO_DEADLK EDEADLK
#else
#define VINBERO_COMMON_ERRNO_DEADLK -EDEADLK
#endif

#if EDEADLOCK <= 0
#define VINBERO_COMMON_ERRNO_DEADLOCK EDEADLOCK
#else
#define VINBERO_COMMON_ERRNO_DEADLOCK -EDEADLOCK
#endif

#if EDESTADDRREQ <= 0
#define VINBERO_COMMON_ERRNO_DESTADDRREQ EDESTADDRREQ
#else
#define VINBERO_COMMON_ERRNO_DESTADDRREQ -EDESTADDRREQ
#endif

#if EDOM <= 0
#define VINBERO_COMMON_ERRNO_DOM EDOM
#else
#define VINBERO_COMMON_ERRNO_DOM -EDOM
#endif

#if EDQUOT <= 0
#define VINBERO_COMMON_ERRNO_DQUOT EDQUOT
#else
#define VINBERO_COMMON_ERRNO_DQUOT -EDQUOT
#endif

#if EEXIST <= 0
#define VINBERO_COMMON_ERRNO_EXIST EEXIST
#else
#define VINBERO_COMMON_ERRNO_EXIST -EEXIST
#endif

#if EFAULT <= 0
#define VINBERO_COMMON_ERRNO_FAULT EFAULT
#else
#define VINBERO_COMMON_ERRNO_FAULT -EFAULT
#endif

#if EFBIG <= 0
#define VINBERO_COMMON_ERRNO_FBIG EFBIG
#else
#define VINBERO_COMMON_ERRNO_FBIG -EFBIG
#endif

#if EHOSTDOWN <= 0
#define VINBERO_COMMON_ERRNO_HOSTDOWN EHOSTDOWN
#else
#define VINBERO_COMMON_ERRNO_HOSTDOWN -EHOSTDOWN
#endif

#if EHOSTUNREACH <= 0
#define VINBERO_COMMON_ERRNO_HOSTUNREACH EHOSTUNREACH
#else
#define VINBERO_COMMON_ERRNO_HOSTUNREACH -EHOSTUNREACH
#endif

#if EHWPOISON <= 0
#define VINBERO_COMMON_ERRNO_HWPOISON EHWPOISON
#else
#define VINBERO_COMMON_ERRNO_HWPOISON -EHWPOISON
#endif

#if EIDRM <= 0
#define VINBERO_COMMON_ERRNO_IDRM EIDRM
#else
#define VINBERO_COMMON_ERRNO_IDRM -EIDRM
#endif

#if EILSEQ <= 0
#define VINBERO_COMMON_ERRNO_ILSEQ EILSEQ
#else
#define VINBERO_COMMON_ERRNO_ILSEQ -EILSEQ
#endif

#if EINPROGRESS <= 0
#define VINBERO_COMMON_ERRNO_INPROGRESS EINPROGRESS
#else
#define VINBERO_COMMON_ERRNO_INPROGRESS -EINPROGRESS
#endif

#if EINTER <= 0
#define VINBERO_COMMON_ERRNO_INTER EINTER
#else
#define VINBERO_COMMON_ERRNO_INTER -EINTER
#endif

#if EINVAL <= 0
#define VINBERO_COMMON_ERRNO_INVAL EINVAL
#else
#define VINBERO_COMMON_ERRNO_INVAL -EINVAL
#endif

#if EIO <= 0
#define VINBERO_COMMON_ERRNO_IO EIO
#else
#define VINBERO_COMMON_ERRNO_IO -EIO
#endif

#if EISCONN <= 0
#define VINBERO_COMMON_ERRNO_ISCONN EISCONN
#else
#define VINBERO_COMMON_ERRNO_ISCONN -EISCONN
#endif

#if EISDIR <= 0
#define VINBERO_COMMON_ERRNO_ISDIR EISDIR
#else
#define VINBERO_COMMON_ERRNO_ISDIR -EISDIR
#endif

#if EISNAM <= 0
#define VINBERO_COMMON_ERRNO_ISNAM EISNAM
#else
#define VINBERO_COMMON_ERRNO_ISNAM -EISNAM
#endif

#if EKEYEXPIRED <= 0
#define VINBERO_COMMON_ERRNO_KEYEXPIRED EKEYEXPIRED
#else
#define VINBERO_COMMON_ERRNO_KEYEXPIRED -EKEYEXPIRED
#endif

#if EKEYREJECTED <= 0
#define VINBERO_COMMON_ERRNO_KEYREJECTED EKEYREJECTED
#else
#define VINBERO_COMMON_ERRNO_KEYREJECTED -EKEYREJECTED
#endif

#if EKEYREVOKED <= 0
#define VINBERO_COMMON_ERRNO_KEYREVOKED EKEYREVOKED
#else
#define VINBERO_COMMON_ERRNO_KEYREVOKED -EKEYREVOKED
#endif

#if EL2HLT <= 0
#define VINBERO_COMMON_ERRNO_L2HLT EL2HLT
#else
#define VINBERO_COMMON_ERRNO_L2HLT -EL2HLT
#endif

#if EL2NSYNC <= 0
#define VINBERO_COMMON_ERRNO_L2NSYNC EL2NSYNC
#else
#define VINBERO_COMMON_ERRNO_L2NSYNC -EL2NSYNC
#endif

#if EL3HLT <= 0
#define VINBERO_COMMON_ERRNO_L3HLT EL3HLT
#else
#define VINBERO_COMMON_ERRNO_L3HLT -EL3HLT
#endif

#if EL3RST <= 0
#define VINBERO_COMMON_ERRNO_L3RST EL3RST
#else
#define VINBERO_COMMON_ERRNO_L3RST -EL3RST
#endif

#if ELIBACC <= 0
#define VINBERO_COMMON_ERRNO_LIBACC ELIBACC
#else
#define VINBERO_COMMON_ERRNO_LIBACC -ELIBACC
#endif

#if ELIBBAD <= 0
#define VINBERO_COMMON_ERRNO_LIBBAD ELIBBAD
#else
#define VINBERO_COMMON_ERRNO_LIBBAD -ELIBBAD
#endif

#if ELIBMAX <= 0
#define VINBERO_COMMON_ERRNO_LIBMAX ELIBMAX
#else
#define VINBERO_COMMON_ERRNO_LIBMAX -ELIBMAX
#endif

#if ELIBSCN <= 0
#define VINBERO_COMMON_ERRNO_LIBSCN ELIBSCN
#else
#define VINBERO_COMMON_ERRNO_LIBSCN -ELIBSCN
#endif

#if ELIBEXEC <= 0
#define VINBERO_COMMON_ERRNO_LIBEXEC ELIBEXEC
#else
#define VINBERO_COMMON_ERRNO_LIBEXEC -ELIBEXEC
#endif

#if ELNRANGE <= 0
#define VINBERO_COMMON_ERRNO_LNRANGE ELNRANGE
#else
#define VINBERO_COMMON_ERRNO_LNRANGE -ELNRANGE
#endif

#if ELOOP <= 0
#define VINBERO_COMMON_ERRNO_LOOP ELOOP
#else
#define VINBERO_COMMON_ERRNO_LOOP -ELOOP
#endif

#if EMEDIUMTYPE <= 0
#define VINBERO_COMMON_ERRNO_MEDIUMTYPE EMEDIUMTYPE
#else
#define VINBERO_COMMON_ERRNO_MEDIUMTYPE -EMEDIUMTYPE
#endif

#if EMFILE <= 0
#define VINBERO_COMMON_ERRNO_MFILE EMFILE
#else
#define VINBERO_COMMON_ERRNO_MFILE -EMFILE
#endif

#if EMLINK <= 0
#define VINBERO_COMMON_ERRNO_MLINK EMLINK
#else
#define VINBERO_COMMON_ERRNO_MLINK -EMLINK
#endif

#if EMSGSIZE <= 0
#define VINBERO_COMMON_ERRNO_MSGSIZE EMSGSIZE
#else
#define VINBERO_COMMON_ERRNO_MSGSIZE -EMSGSIZE
#endif

#if EMULTIHOP <= 0
#define VINBERO_COMMON_ERRNO_MULTIHOP EMULTIHOP
#else
#define VINBERO_COMMON_ERRNO_MULTIHOP -EMULTIHOP
#endif

#if ENAMETOOLONG <= 0
#define VINBERO_COMMON_ERRNO_NAMETOOLONG ENAMETOOLONG
#else
#define VINBERO_COMMON_ERRNO_NAMETOOLONG -ENAMETOOLONG
#endif

#if ENETDOWN <= 0
#define VINBERO_COMMON_ERRNO_NETDOWN ENETDOWN
#else
#define VINBERO_COMMON_ERRNO_NETDOWN -ENETDOWN
#endif

#if ENETRESET <= 0
#define VINBERO_COMMON_ERRNO_NETRESET ENETRESET
#else
#define VINBERO_COMMON_ERRNO_NETRESET -ENETRESET
#endif

#if ENETUNREACH <= 0
#define VINBERO_COMMON_ERRNO_NETUNREACH ENETUNREACH
#else
#define VINBERO_COMMON_ERRNO_NETUNREACH -ENETUNREACH
#endif

#if ENFILE <= 0
#define VINBERO_COMMON_ERRNO_NFILE ENFILE
#else
#define VINBERO_COMMON_ERRNO_NFILE -ENFILE
#endif

#if ENOANO <= 0
#define VINBERO_COMMON_ERRNO_NOANO ENOANO
#else
#define VINBERO_COMMON_ERRNO_NOANO -ENOANO
#endif
 
#if ENOBUFS <= 0
#define VINBERO_COMMON_ERRNO_NOBUFS ENOBUFS
#else
#define VINBERO_COMMON_ERRNO_NOBUFS -ENOBUFS
#endif
 
#if ENODATA <= 0
#define VINBERO_COMMON_ERRNO_NODATA ENODATA
#else
#define VINBERO_COMMON_ERRNO_NODATA -ENODATA
#endif

#if ENODEV <= 0
#define VINBERO_COMMON_ERRNO_NODEV ENODEV
#else
#define VINBERO_COMMON_ERRNO_NODEV -ENODEV
#endif

#if ENOENT <= 0
#define VINBERO_COMMON_ERRNO_NOENT ENOENT
#else
#define VINBERO_COMMON_ERRNO_NOENT -ENOENT
#endif

#if ENOEXEC <= 0
#define VINBERO_COMMON_ERRNO_NOEXEC ENOEXEC
#else
#define VINBERO_COMMON_ERRNO_NOEXEC -ENOEXEC
#endif

#if ENOKEY <= 0
#define VINBERO_COMMON_ERRNO_NOKEY ENOKEY
#else
#define VINBERO_COMMON_ERRNO_NOKEY -ENOKEY
#endif

#if ENOLCK <= 0
#define VINBERO_COMMON_ERRNO_NOLCK ENOLCK
#else
#define VINBERO_COMMON_ERRNO_NOLCK -ENOLCK
#endif

#if ENOLINK <= 0
#define VINBERO_COMMON_ERRNO_NOLINK ENOLINK
#else
#define VINBERO_COMMON_ERRNO_NOLINK -ENOLINK
#endif

#if ENOMEDIUM <= 0
#define VINBERO_COMMON_ERRNO_NOMEDIUM ENOMEDIUM
#else
#define VINBERO_COMMON_ERRNO_NOMEDIUM -ENOMEDIUM
#endif

#if ENOMEM <= 0
#define VINBERO_COMMON_ERRNO_NOMEM ENOMEM
#else
#define VINBERO_COMMON_ERRNO_NOMEM -ENOMEM
#endif

#if ENOMSG <= 0
#define VINBERO_COMMON_ERRNO_NOMSG ENOMSG
#else
#define VINBERO_COMMON_ERRNO_NOMSG -ENOMSG
#endif

#if ENONET <= 0
#define VINBERO_COMMON_ERRNO_NONET ENONET
#else
#define VINBERO_COMMON_ERRNO_NONET -ENONET
#endif

#if ENOPKG <= 0
#define VINBERO_COMMON_ERRNO_NOPKG ENOPKG
#else
#define VINBERO_COMMON_ERRNO_NOPKG -ENOPKG
#endif

#if ENOPROTOOPT <= 0
#define VINBERO_COMMON_ERRNO_NOPROTOOPT ENOPROTOOPT
#else
#define VINBERO_COMMON_ERRNO_NOPROTOOPT -ENOPROTOOPT
#endif

#if ENOSPC <= 0
#define VINBERO_COMMON_ERRNO_NOSPC ENOSPC
#else
#define VINBERO_COMMON_ERRNO_NOSPC -ENOSPC
#endif

#if ENOSR <= 0
#define VINBERO_COMMON_ERRNO_NOSR ENOSR
#else
#define VINBERO_COMMON_ERRNO_NOSR -ENOSR
#endif

#if ENOSTR <= 0
#define VINBERO_COMMON_ERRNO_NOSTR ENOSTR
#else
#define VINBERO_COMMON_ERRNO_NOSTR -ENOSTR
#endif

#if ENOSYS <= 0
#define VINBERO_COMMON_ERRNO_NOSYS ENOSYS
#else
#define VINBERO_COMMON_ERRNO_NOSYS -ENOSYS
#endif

#if ENOTBLK <= 0
#define VINBERO_COMMON_ERRNO_NOTBLK ENOTBLK
#else
#define VINBERO_COMMON_ERRNO_NOTBLK -ENOTBLK
#endif

#if ENOTCONN <= 0
#define VINBERO_COMMON_ERRNO_NOTCONN ENOTCONN
#else
#define VINBERO_COMMON_ERRNO_NOTCONN -ENOTCONN
#endif

#if ENOTDIR <= 0
#define VINBERO_COMMON_ERRNO_NOTDIR ENOTDIR
#else
#define VINBERO_COMMON_ERRNO_NOTDIR -ENOTDIR
#endif

#if ENOTEMPTY <= 0
#define VINBERO_COMMON_ERRNO_NOTEMPTY ENOTEMPTY
#else
#define VINBERO_COMMON_ERRNO_NOTEMPTY -ENOTEMPTY
#endif

#if ENOTRECOVERABLE <= 0
#define VINBERO_COMMON_ERRNO_NOTRECOVERABLE ENOTRECOVERABLE
#else
#define VINBERO_COMMON_ERRNO_NOTRECOVERABLE -ENOTRECOVERABLE
#endif

#if ENOTSOCK <= 0
#define VINBERO_COMMON_ERRNO_NOTSOCK ENOTSOCK
#else
#define VINBERO_COMMON_ERRNO_NOTSOCK -ENOTSOCK
#endif

#if ENOTSUP <= 0
#define VINBERO_COMMON_ERRNO_NOTSUP ENOTSUP
#else
#define VINBERO_COMMON_ERRNO_NOTSUP -ENOTSUP
#endif

#if ENOTTY <= 0
#define VINBERO_COMMON_ERRNO_NOTTY ENOTTY
#else
#define VINBERO_COMMON_ERRNO_NOTTY -ENOTTY
#endif

#if ENOTUNIQ <= 0
#define VINBERO_COMMON_ERRNO_NOTUNIQ ENOTUNIQ
#else
#define VINBERO_COMMON_ERRNO_NOTUNIQ -ENOTUNIQ
#endif
 
#if ENXIO <= 0
#define VINBERO_COMMON_ERRNO_NXIO ENXIO
#else
#define VINBERO_COMMON_ERRNO_NXIO -ENXIO
#endif

#if EOPNOTSUPP <= 0
#define VINBERO_COMMON_ERRNO_OPNOTSUPP EOPNOTSUPP
#else
#define VINBERO_COMMON_ERRNO_OPNOTSUPP -EOPNOTSUPP
#endif

#if EOVERFLOW <= 0
#define VINBERO_COMMON_ERRNO_OVERFLOW EOVERFLOW
#else
#define VINBERO_COMMON_ERRNO_OVERFLOW -EOVERFLOW
#endif

#if EOWNERDEAD <= 0
#define VINBERO_COMMON_ERRNO_OWNERDEAD EOWNERDEAD
#else
#define VINBERO_COMMON_ERRNO_OWNERDEAD -EOWNERDEAD
#endif

#if EPERM <= 0
#define VINBERO_COMMON_ERRNO_PERM EPERM
#else
#define VINBERO_COMMON_ERRNO_PERM -EPERM
#endif

#if EPFNOSUPPORT <= 0
#define VINBERO_COMMON_ERRNO_PFNOSUPPORT EPFNOSUPPORT
#else
#define VINBERO_COMMON_ERRNO_PFNOSUPPORT -EPFNOSUPPORT
#endif

#if EPIPE <= 0
#define VINBERO_COMMON_ERRNO_PIPE EPIPE
#else
#define VINBERO_COMMON_ERRNO_PIPE -EPIPE
#endif

#if EPROTO <= 0
#define VINBERO_COMMON_ERRNO_PROTO EPROTO
#else
#define VINBERO_COMMON_ERRNO_PROTO -EPROTO
#endif

#if EPROTONOSUPPORT <= 0
#define VINBERO_COMMON_ERRNO_PROTONOSUPPORT EPROTONOSUPPORT
#else
#define VINBERO_COMMON_ERRNO_PROTONOSUPPORT -EPROTONOSUPPORT
#endif

#if EPROTOTYPE <= 0
#define VINBERO_COMMON_ERRNO_PROTOTYPE EPROTOTYPE
#else
#define VINBERO_COMMON_ERRNO_PROTOTYPE -EPROTOTYPE
#endif

#if ERANGE <= 0
#define VINBERO_COMMON_ERRNO_RANGE ERANGE
#else
#define VINBERO_COMMON_ERRNO_RANGE -ERANGE
#endif

#if EREMCHG <= 0
#define VINBERO_COMMON_ERRNO_REMCHG EREMCHG
#else
#define VINBERO_COMMON_ERRNO_REMCHG -EREMCHG
#endif

#if EREMOTE <= 0
#define VINBERO_COMMON_ERRNO_REMOTE EREMOTE
#else
#define VINBERO_COMMON_ERRNO_REMOTE -EREMOTE
#endif

#if EREMOTEIO <= 0
#define VINBERO_COMMON_ERRNO_REMOTEIO EREMOTEIO
#else
#define VINBERO_COMMON_ERRNO_REMOTEIO -EREMOTEIO
#endif

#if ERESTART <= 0
#define VINBERO_COMMON_ERRNO_RESTART ERESTART
#else
#define VINBERO_COMMON_ERRNO_RESTART -ERESTART
#endif

#if ERFKILL <= 0
#define VINBERO_COMMON_ERRNO_RFKILL ERFKILL
#else
#define VINBERO_COMMON_ERRNO_RFKILL -ERFKILL
#endif

#if EROFS <= 0
#define VINBERO_COMMON_ERRNO_ROFS EROFS
#else
#define VINBERO_COMMON_ERRNO_ROFS -EROFS
#endif

#if ESHUTDOWN <= 0
#define VINBERO_COMMON_ERRNO_SHUTDOWN ESHUTDOWN
#else
#define VINBERO_COMMON_ERRNO_SHUTDOWN -ESHUTDOWN
#endif
 
#if ESPIPE <= 0
#define VINBERO_COMMON_ERRNO_SPIPE ESPIPE
#else
#define VINBERO_COMMON_ERRNO_SPIPE -ESPIPE
#endif

#if ESOCKTNOSUPPORT <= 0
#define VINBERO_COMMON_ERRNO_SOCKTNOSUPPORT ESOCKTNOSUPPORT
#else
#define VINBERO_COMMON_ERRNO_SOCKTNOSUPPORT -ESOCKTNOSUPPORT
#endif

#if ESRCH <= 0
#define VINBERO_COMMON_ERRNO_SRCH ESRCH
#else
#define VINBERO_COMMON_ERRNO_SRCH -ESRCH
#endif

#if ESTALE <= 0
#define VINBERO_COMMON_ERRNO_STALE ESTALE
#else
#define VINBERO_COMMON_ERRNO_STALE -ESTALE
#endif

#if ESTRPIPE <= 0
#define VINBERO_COMMON_ERRNO_STRPIPE ESTRPIPE
#else
#define VINBERO_COMMON_ERRNO_STRPIPE -ESTRPIPE
#endif

#if ETIME <= 0
#define VINBERO_COMMON_ERRNO_TIME ETIME
#else
#define VINBERO_COMMON_ERRNO_TIME -ETIME
#endif

#if ETIMEDOUT <= 0
#define VINBERO_COMMON_ERRNO_TIMEDOUT ETIMEDOUT
#else
#define VINBERO_COMMON_ERRNO_TIMEDOUT -ETIMEDOUT
#endif

#if ETOOMANYREFS <= 0
#define VINBERO_COMMON_ERRNO_TOOMANYREFS ETOOMANYREFS
#else
#define VINBERO_COMMON_ERRNO_TOOMANYREFS -ETOOMANYREFS
#endif

#if ETXTBSY <= 0
#define VINBERO_COMMON_ERRNO_TXTBSY ETXTBSY
#else
#define VINBERO_COMMON_ERRNO_TXTBSY -ETXTBSY
#endif

#if EUCLEAN <= 0
#define VINBERO_COMMON_ERRNO_UCLEAN EUCLEAN
#else
#define VINBERO_COMMON_ERRNO_UCLEAN -EUCLEAN
#endif

#if EUNATCH <= 0
#define VINBERO_COMMON_ERRNO_UNATCH EUNATCH
#else
#define VINBERO_COMMON_ERRNO_UNATCH -EUNATCH
#endif

#if EUSERS <= 0
#define VINBERO_COMMON_ERRNO_USERS EUSERS
#else
#define VINBERO_COMMON_ERRNO_USERS -EUSERS
#endif

#if EWOULDBLOCK <= 0
#define VINBERO_COMMON_ERRNO_WOULDBLOCK EWOULDBLOCK
#else
#define VINBERO_COMMON_ERRNO_WOULDBLOCK -EWOULDBLOCK
#endif
 
#if EXDEV <= 0
#define VINBERO_COMMON_ERRNO_XDEV EXDEV
#else
#define VINBERO_COMMON_ERRNO_XDEV -EXDEV
#endif

#if EXFULL <= 0
#define VINBERO_COMMON_ERRNO_XFULL EXFULL
#else
#define VINBERO_COMMON_ERRNO_XFULL -EXFULL
#endif

#endif
